import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, writeFile, readFile, rm, unlink } from 'node:fs/promises';
import path from 'node:path';
import { tmpdir } from 'node:os';
import {
  YASREADY_AUDIOBOOKS_VERSION,
  sha256,
  stableJson,
  buildBookOneProductionPlan,
  buildBookOneProductionRecipeLock,
  runBookOneFullBookPreflight,
  buildBookOneDistributionOutputContract,
  selectBookOneWholeChapterBatch,
  buildBookOneQuotaAwareBatchArm,
  verifyBookOneQuotaAwareBatchArm,
  renderBookOneQuotaAwareBatch,
  verifyBookOneBatchProductionResult,
  getMasteringProfile,
  getDistributionProfile,
  ElevenLabsApiError
} from '../src/index.js';

function narratorLock() {
  const core={schemaVersion:1,release:'0.14.3.12',artifact:'book-one-narrator-production-lock',status:'LOCKED_FOR_PRODUCTION_PLANNING',book:{id:'book-one',title:'Fixture Book',author:'Fixture Author',sourceHash:'fixture-source-hash'},narrator:{provider:'elevenlabs',providerVoiceId:'rU18Fk3uSDhmg5Xh41o4',candidateName:'Ryan Kurk - Pleasant and Smooth'},performanceProfile:{baseDirectionId:'playful-flirty',baseDirectionLabel:'Playful + Flirty',emotionalVariantId:'deep-controlled-emotion',emotionalVariantLabel:'Deep Controlled Emotion',stability:0.24,providerVoiceSettings:{speed:1.2,stability:0.24},paceProfile:{providerNativeSpeed:1.2,effectiveSpeed:1.25,postProcessTempoMultiplier:1.041667,postProcessRequired:true,postProcessKind:'ffmpeg-atempo',pitchPreservingPostProcess:true}},productionArmed:false,fullBookGenerationArmed:false};
  return {...core,lockDigest:sha256(stableJson(core))};
}
function finalization(){const lock=narratorLock();return{schemaVersion:1,release:'0.14.3.12',artifact:'book-one-pace-ceiling-finalization',status:'PASSED',decision:'pass',book:lock.book,narratorProductionLockCreated:true,productionArmed:false,fullBookGenerationArmed:false,narratorProductionLock:lock};}
function analysis(){
  const seg=(order,text)=>({order,paragraphIndex:order,kind:'narration',text,speakerCandidate:null});
  const ch=(order,title,text)=>({order,title,textHash:sha256(text),scenes:[{order:0,textHash:sha256(text),segments:[seg(0,text)]}]});
  const texts=[
    'Chapter one begins warmly. '.repeat(22),
    'Chapter two carries the story forward. '.repeat(26),
    'Chapter three is longer and emotional. '.repeat(38),
    'Chapter four closes this fixture batch. '.repeat(42)
  ];
  return{schemaVersion:3,source:{format:'docx',filename:'book.docx',sourceHash:'fixture-source-hash',normalizedTextHash:'n'},metadata:{title:'Fixture Book',author:'Fixture Author'},metrics:{words:5000,chapters:4,scenes:4,segments:4,estimatedMinutesAt155Wpm:32},chapters:texts.map((t,i)=>ch(i,`Chapter ${i+1}`,t))};
}
function plan(){return buildBookOneProductionPlan({paceCeilingFinalization:finalization(),manuscriptAnalysis:analysis(),explicitChunkCap:450,rateUsdPer1kCharacters:0.10,retryReserveRatio:0.20});}
function finishLock(){const p=plan();const core={schemaVersion:1,release:'0.14.3.14.2',artifact:'book-one-local-voice-finish-lock',status:'LOCKED_FOR_PRODUCTION_PLANNING_ONLY',sourcePilotRenderDigest:'pilot-render',narrator:{provider:'elevenlabs',providerVoiceId:p.productionRecipe.providerVoiceId,narratorName:p.productionRecipe.narratorName},performanceUnchanged:true,providerVoiceSettingsUnchanged:p.productionRecipe.providerVoiceSettings,paceProfileUnchanged:p.productionRecipe.paceProfile,selectedVariant:{id:'warm-slightly-deeper',label:'Warm + Slightly Deeper',kind:'local-tone-and-pitch',eq:{bodyHz:180,bodyDb:1.2,presenceHz:3000,presenceDb:-1.6,airHz:5200,airDb:-0.8},semitones:-0.5,pitchFactor:0.971531941,durationCompensation:1.029302237,formantPreservationClaimed:false},productionArmed:false,fullBookGenerationArmed:false};return{...core,finishDigest:sha256(stableJson(core))};}
function provider(remaining=1000000){let calls=0;return{get calls(){return calls;},healthCheck:async()=>({ok:true,status:200}),subscriptionPreflight:async()=>({available:true,safeToContinue:true,tier:'creator',status:'active',subscription:{tier:'creator',status:'active',character_count:1000,character_limit:1000+remaining}}),render:async({text})=>{calls+=1;return{audio:new Uint8Array(Buffer.from(`audio:${text.length}:${calls}`)),billedCharacters:text.length,estimatedCostUsd:(text.length/1000)*0.10,requestId:`req-${calls}`};}};}
function ffmpeg({failVoiceDepthOnce=false,badQa=false}={}){let failed=false;const write=async(out,label)=>{await mkdir(path.dirname(out),{recursive:true});await writeFile(out,Buffer.from(label));return out;};return{healthCheck:async()=>({ok:true,ffmpeg:'ffmpeg fixture',ffprobe:'ffprobe fixture'}),tempo:async(i,o,m)=>{await write(o,`tempo:${m}:${await readFile(i,'utf8')}`);return{outputPath:o};},voiceDepth:async(i,o,{mode})=>{if(failVoiceDepthOnce&&!failed){failed=true;throw new Error('fixture local finish fail');}await write(o,`finish:${mode}:${await readFile(i,'utf8')}`);return{outputPath:o};},concat:async(inputs,o)=>{const parts=[];for(const f of inputs)parts.push(await readFile(f,'utf8'));await write(o,parts.join('|'));return o;},master:async(i,o,profile)=>{await write(o,`master:${profile}:${await readFile(i,'utf8')}`);return{outputPath:o};},analyze:async(file)=>({durationSec:60,sampleRateHz:44100,channels:1,channelLayout:'mono',codec:file.endsWith('.wav')?'pcm_s24le':'mp3',bitrateKbps:file.endsWith('.mp3')?192:null,rmsDb:-20.5,peakDb:-4,noiseFloorDb:-70,leadingSilenceMs:1200,trailingSilenceMs:1200})};}
const disk=(g=100)=>async(root)=>({root,availableBytes:g*1024**3,availableGiB:g});
async function recipeAndPreflight({remaining=1000000,badFfmpeg=false}={}){const p=plan(),f=finishLock();const recipe=buildBookOneProductionRecipeLock({productionPlan:p,localVoiceFinishLock:f});const ff=badFfmpeg?{healthCheck:async()=>({ok:false,reason:'missing'})}:ffmpeg();const {preflight}=await runBookOneFullBookPreflight({productionPlan:p,localVoiceFinishLock:f,provider:provider(remaining),ffmpeg:ff,outputRoot:'/tmp/yasready-preflight-fixture',storageProbe:disk(100)});return{p,f,recipe,preflight};}

// Release + current retailer contract

test('0.14.3.16 is current application provenance',()=>assert.equal(YASREADY_AUDIOBOOKS_VERSION,'0.14.3.16'));
test('ACX technical profile enforces one-file chapter output under 120 minutes at 192 CBR / 44.1 kHz',()=>{const m=getMasteringProfile('acx-2026');const d=getDistributionProfile('acx-2026');assert.equal(m.output.bitrateKbps,192);assert.equal(m.output.sampleRateHz,44100);assert.equal(m.output.cbr,true);assert.equal(m.maxSectionDurationSec,7200);assert.equal(d.audio.maxSectionDurationSec,7200);assert.equal(d.sample,'required');assert.equal(d.sampleMaxDurationSec,300);assert.equal(d.digitalNarration,'explicit-authorization-required');});
test('distribution contract preserves retailer-specific digital narration truth',()=>{const c=buildBookOneDistributionOutputContract();const acx=c.targets.find(x=>x.id==='acx-2026');const sp=c.targets.find(x=>x.id==='spotify-direct-2026');const ap=c.targets.find(x=>x.id==='apple-partner-2026');assert.match(acx.eligibility,/EXPLICITLY_AUTHORIZES/);assert.match(sp.eligibility,/ACCEPTED_WITH_DISCLOSURE/);assert.match(ap.eligibility,/PREFERRED_PARTNER/);assert.equal(c.guardrails.retailerAcceptanceNeverInferredFromTechnicalEncode,true);assert.equal(c.sharedRetailChapterMaster.spokenChapterOrSectionHeadingIncluded,true);const spotify=getDistributionProfile('spotify-direct-2026');for(const field of ['bisac','territories','priceUsd'])assert.ok(spotify.metadata.required.includes(field));assert.equal(spotify.metadata.isbn,'optional');assert.equal(spotify.metadata.required.includes('isbn13'),false);});

test('quota selector takes only whole sequential chapters and reserves retry characters',()=>{const p=plan();const first=p.manifest.chapters[0];const headingChars='Chapter 1.'.length;const direct=first.providerCharacters+headingChars;const limit=direct+Math.ceil(direct*.2)+5;const s=selectBookOneWholeChapterBatch({productionPlan:p,providerRemaining:limit,retryReserveRatio:.2});assert.equal(s.selectedChapterCount,1);assert.equal(s.selectedChapters[0].title,'Chapter 1');assert.ok(s.retryReserveCharacters>0);assert.ok(s.quotaEnvelopeCharacters<=limit);});
test('batch selector obeys an independent chapter-count safety cap even when quota could fit more',()=>{const p=plan();const s=selectBookOneWholeChapterBatch({productionPlan:p,providerRemaining:1000000,retryReserveRatio:.2,maxChapters:2});assert.equal(s.selectedChapterCount,2);assert.equal(s.lastChapterOrder,1);});

test('verified pilot-paid body chunks reduce new quota work while the required spoken chapter heading remains new work',()=>{const p=plan();const first=p.manifest.chapters[0];const reuse=first.chunks.map(ch=>({id:ch.id}));const s=selectBookOneWholeChapterBatch({productionPlan:p,providerRemaining:100,retryReserveRatio:.2,reusableChunks:reuse});const firstScope=s.selectedChapters[0];assert.equal(firstScope.bodyNewProviderCharacters,0);assert.equal(firstScope.newProviderCharacters,firstScope.spokenChapterHeading.characters);assert.equal(firstScope.newProviderCalls,1);assert.equal(firstScope.reusableProviderCharacters,first.providerCharacters);});

test('batch arm is zero-spend and exact-scope only even when full-book preflight is quota-blocked',async()=>{const {p,recipe,preflight}=await recipeAndPreflight({remaining:1200});assert.equal(preflight.status,'BLOCKED_NOT_READY_FOR_FULL_BOOK_ARM');const pr=provider(1200);const arm=await buildBookOneQuotaAwareBatchArm({productionPlan:p,recipeLock:recipe,preflight,provider:pr,ffmpeg:ffmpeg(),outputRoot:'/tmp/yasready-batch-arm',storageProbe:disk(100)});assert.equal(verifyBookOneQuotaAwareBatchArm(arm),true);assert.match(arm.confirmation.token,/^BATCH-[A-F0-9]{10}$/);assert.equal(arm.guardrails.armProviderTtsCalls,0);assert.equal(arm.guardrails.maxChaptersPerBatch,10);assert.ok(arm.batchScope.selectedChapterCount<=10);assert.equal(pr.calls,0);assert.equal(arm.guardrails.fullBookGenerationArmed,false);});

test('batch arm refuses non-quota blockers instead of bypassing full-book preflight',async()=>{const {p,recipe,preflight}=await recipeAndPreflight({remaining:1000000,badFfmpeg:true});assert.ok(preflight.blockers.some(x=>x.id==='ffmpeg-health'));await assert.rejects(()=>buildBookOneQuotaAwareBatchArm({productionPlan:p,recipeLock:recipe,preflight,provider:provider(),ffmpeg:ffmpeg(),outputRoot:'/tmp/yasready-batch-arm',storageProbe:disk(100)}),/cannot bypass non-quota/i);});

test('batch protected max includes retry reserve before any paid render',async()=>{const {p,recipe,preflight}=await recipeAndPreflight();const arm=await buildBookOneQuotaAwareBatchArm({productionPlan:p,recipeLock:recipe,preflight,provider:provider(),ffmpeg:ffmpeg(),outputRoot:'/tmp/yasready-batch-arm',storageProbe:disk(100)});assert.ok(arm.budget.retryReserveUsd>0);assert.ok(arm.budget.protectedMaxUsd>=arm.budget.initialGenerationUsd+arm.budget.retryReserveUsd-0.009);});

test('PREFLIGHT token can never authorize batch spend',async()=>{const {p,recipe,preflight}=await recipeAndPreflight();const arm=await buildBookOneQuotaAwareBatchArm({productionPlan:p,recipeLock:recipe,preflight,provider:provider(),ffmpeg:ffmpeg(),outputRoot:'/tmp/yasready-batch-arm',storageProbe:disk(100)});const dir=await mkdtemp(path.join(tmpdir(),'yasready-batch-token-'));try{const pr=provider();await assert.rejects(()=>renderBookOneQuotaAwareBatch({productionPlan:p,recipeLock:recipe,preflight,arm,manuscriptAnalysis:analysis(),provider:pr,ffmpeg:ffmpeg(),outputRoot:dir,approvalToken:preflight.confirmation.token,maxUsd:arm.budget.protectedMaxUsd}),/Exact BATCH approval token/i);assert.equal(pr.calls,0);}finally{await rm(dir,{recursive:true,force:true});}});

test('approved batch renders only armed whole chapters and creates retailer-aware derivatives',async()=>{const {p,recipe,preflight}=await recipeAndPreflight();const arm=await buildBookOneQuotaAwareBatchArm({productionPlan:p,recipeLock:recipe,preflight,provider:provider(),ffmpeg:ffmpeg(),outputRoot:'/tmp/yasready-batch-arm',storageProbe:disk(100)});const dir=await mkdtemp(path.join(tmpdir(),'yasready-batch-render-'));try{const pr=provider();const result=await renderBookOneQuotaAwareBatch({productionPlan:p,recipeLock:recipe,preflight,arm,manuscriptAnalysis:analysis(),provider:pr,ffmpeg:ffmpeg(),outputRoot:dir,approvalToken:arm.confirmation.token,maxUsd:arm.budget.protectedMaxUsd});assert.equal(verifyBookOneBatchProductionResult(result),true);assert.equal(result.batch.chapterCount,arm.batchScope.selectedChapterCount);assert.equal(result.guardrails.fullBookGenerationArmed,false);assert.equal(result.guardrails.nextBatchArmed,false);assert.equal(result.distribution.finalPackageComplete,false);assert.equal(result.distribution.acx.technicalChapterFilesReady,true);assert.equal(result.distribution.spotify.technicalChapterFilesReady,true);assert.equal(result.distribution.apple.losslessPartnerSourceFilesReady,true);for(const ch of result.chapters){assert.match(ch.spokenChapterHeading,/^Chapter /);assert.ok(await readFile(path.join(dir,ch.outputs.archiveWav)));assert.ok(await readFile(path.join(dir,ch.outputs.acxMp3)));assert.ok(await readFile(path.join(dir,ch.outputs.spotifyMp3)));assert.ok(await readFile(path.join(dir,ch.outputs.applePartnerWav)));}const state=JSON.parse(await readFile(path.join(dir,'batch-one-production-state.json'),'utf8'));assert.ok(Object.keys(state.chunks).some((id)=>id.endsWith('-heading')));}finally{await rm(dir,{recursive:true,force:true});}});

test('local voice-finish failure resumes without repaying provider TTS',async()=>{const {p,recipe,preflight}=await recipeAndPreflight({remaining:1500});const arm=await buildBookOneQuotaAwareBatchArm({productionPlan:p,recipeLock:recipe,preflight,provider:provider(1500),ffmpeg:ffmpeg(),outputRoot:'/tmp/yasready-batch-arm',storageProbe:disk(100)});const dir=await mkdtemp(path.join(tmpdir(),'yasready-batch-resume-'));try{const firstProvider=provider(1500);await assert.rejects(()=>renderBookOneQuotaAwareBatch({productionPlan:p,recipeLock:recipe,preflight,arm,manuscriptAnalysis:analysis(),provider:firstProvider,ffmpeg:ffmpeg({failVoiceDepthOnce:true}),outputRoot:dir,approvalToken:arm.confirmation.token,maxUsd:arm.budget.protectedMaxUsd}),/fixture local finish fail/);assert.equal(firstProvider.calls,1);const secondProvider=provider(1500);await renderBookOneQuotaAwareBatch({productionPlan:p,recipeLock:recipe,preflight,arm,manuscriptAnalysis:analysis(),provider:secondProvider,ffmpeg:ffmpeg(),outputRoot:dir,approvalToken:arm.confirmation.token,maxUsd:arm.budget.protectedMaxUsd});assert.equal(firstProvider.calls+secondProvider.calls,arm.batchScope.newProviderCalls);assert.ok(secondProvider.calls<arm.batchScope.newProviderCalls);}finally{await rm(dir,{recursive:true,force:true});}});

test('render rechecks quota with retry headroom rather than consuming the entire live balance',async()=>{const {p,recipe,preflight}=await recipeAndPreflight({remaining:1500});const arm=await buildBookOneQuotaAwareBatchArm({productionPlan:p,recipeLock:recipe,preflight,provider:provider(1500),ffmpeg:ffmpeg(),outputRoot:'/tmp/yasready-batch-arm',storageProbe:disk(100)});const direct=arm.batchScope.newProviderCharacters;assert.ok(arm.batchScope.retryReserveCharacters>0);const dir=await mkdtemp(path.join(tmpdir(),'yasready-batch-quota-recheck-'));try{const pr=provider(direct);await assert.rejects(()=>renderBookOneQuotaAwareBatch({productionPlan:p,recipeLock:recipe,preflight,arm,manuscriptAnalysis:analysis(),provider:pr,ffmpeg:ffmpeg(),outputRoot:dir,approvalToken:arm.confirmation.token,maxUsd:arm.budget.protectedMaxUsd}),/plus retry reserve/i);assert.equal(pr.calls,0);}finally{await rm(dir,{recursive:true,force:true});}});

test('an arm that counted paid pilot reuse refuses to repurchase those chunks if reuse evidence disappears',async()=>{const {p,recipe,preflight}=await recipeAndPreflight({remaining:1500});const first=p.manifest.chapters[0];const fakeReuse={available:true,sourcePilotRenderDigest:recipe.source.sourcePilotRenderDigest,reusableCalls:first.chunks.length,reusableCharacters:first.providerCharacters,reusableChunks:first.chunks.map((ch)=>({id:ch.id,generationDigest:ch.generationDigest,audioSha256:`sha-${ch.id}`,characters:ch.characters,sourceProviderPath:`/tmp/not-used-${ch.id}`}))};const arm=await buildBookOneQuotaAwareBatchArm({productionPlan:p,recipeLock:recipe,preflight,provider:provider(1500),ffmpeg:ffmpeg(),outputRoot:'/tmp/yasready-batch-arm',pilotReuse:fakeReuse,storageProbe:disk(100)});assert.ok(arm.batchScope.reusableProviderCalls>0);const dir=await mkdtemp(path.join(tmpdir(),'yasready-batch-reuse-missing-'));try{const pr=provider(1500);await assert.rejects(()=>renderBookOneQuotaAwareBatch({productionPlan:p,recipeLock:recipe,preflight,arm,manuscriptAnalysis:analysis(),provider:pr,ffmpeg:ffmpeg(),outputRoot:dir,approvalToken:arm.confirmation.token,maxUsd:arm.budget.protectedMaxUsd,pilotReuse:null}),/depends on verified paid pilot reuse/i);assert.equal(pr.calls,0);}finally{await rm(dir,{recursive:true,force:true});}});


test('provider 5xx outcome is treated as unknown and never auto-retried',async()=>{const {p,recipe,preflight}=await recipeAndPreflight({remaining:1500});const arm=await buildBookOneQuotaAwareBatchArm({productionPlan:p,recipeLock:recipe,preflight,provider:provider(1500),ffmpeg:ffmpeg(),outputRoot:'/tmp/yasready-batch-arm',storageProbe:disk(100)});const dir=await mkdtemp(path.join(tmpdir(),'yasready-batch-provider-unknown-'));try{let attempted=0;const failing={healthCheck:async()=>({ok:true,status:200}),subscriptionPreflight:async()=>({available:true,safeToContinue:true,tier:'creator',status:'active',subscription:{tier:'creator',status:'active',character_count:1000,character_limit:2500}}),render:async()=>{attempted+=1;throw new ElevenLabsApiError('fixture provider server failure',{status:500,requestId:'req-uncertain'});}};await assert.rejects(()=>renderBookOneQuotaAwareBatch({productionPlan:p,recipeLock:recipe,preflight,arm,manuscriptAnalysis:analysis(),provider:failing,ffmpeg:ffmpeg(),outputRoot:dir,approvalToken:arm.confirmation.token,maxUsd:arm.budget.protectedMaxUsd}),/DO NOT RERUN PROVIDER/i);assert.equal(attempted,1);const retry=provider(1500);await assert.rejects(()=>renderBookOneQuotaAwareBatch({productionPlan:p,recipeLock:recipe,preflight,arm,manuscriptAnalysis:analysis(),provider:retry,ffmpeg:ffmpeg(),outputRoot:dir,approvalToken:arm.confirmation.token,maxUsd:arm.budget.protectedMaxUsd}),/DO NOT RERUN PROVIDER/i);assert.equal(retry.calls,0);}finally{await rm(dir,{recursive:true,force:true});}});

test('missing settled paid provider audio fails DO NOT RERUN instead of silently buying a replacement',async()=>{const {p,recipe,preflight}=await recipeAndPreflight({remaining:1500});const arm=await buildBookOneQuotaAwareBatchArm({productionPlan:p,recipeLock:recipe,preflight,provider:provider(1500),ffmpeg:ffmpeg(),outputRoot:'/tmp/yasready-batch-arm',storageProbe:disk(100)});const dir=await mkdtemp(path.join(tmpdir(),'yasready-batch-paid-file-loss-'));try{await renderBookOneQuotaAwareBatch({productionPlan:p,recipeLock:recipe,preflight,arm,manuscriptAnalysis:analysis(),provider:provider(1500),ffmpeg:ffmpeg(),outputRoot:dir,approvalToken:arm.confirmation.token,maxUsd:arm.budget.protectedMaxUsd});const state=JSON.parse(await readFile(path.join(dir,'batch-one-production-state.json'),'utf8'));const paid=Object.values(state.chunks).find((row)=>row.billingBasis!=='historical-paid-pilot-reuse');assert.ok(paid);await unlink(path.join(dir,paid.providerRelativePath));const retry=provider(1500);await assert.rejects(()=>renderBookOneQuotaAwareBatch({productionPlan:p,recipeLock:recipe,preflight,arm,manuscriptAnalysis:analysis(),provider:retry,ffmpeg:ffmpeg(),outputRoot:dir,approvalToken:arm.confirmation.token,maxUsd:arm.budget.protectedMaxUsd}),/DO NOT RERUN PROVIDER: paid provider audio is missing/i);assert.equal(retry.calls,0);}finally{await rm(dir,{recursive:true,force:true});}});

test('batch result never claims retailer submission is complete',async()=>{const {p,recipe,preflight}=await recipeAndPreflight({remaining:1500});const arm=await buildBookOneQuotaAwareBatchArm({productionPlan:p,recipeLock:recipe,preflight,provider:provider(1500),ffmpeg:ffmpeg(),outputRoot:'/tmp/yasready-batch-arm',storageProbe:disk(100)});const dir=await mkdtemp(path.join(tmpdir(),'yasready-batch-retailer-'));try{const result=await renderBookOneQuotaAwareBatch({productionPlan:p,recipeLock:recipe,preflight,arm,manuscriptAnalysis:analysis(),provider:provider(1500),ffmpeg:ffmpeg(),outputRoot:dir,approvalToken:arm.confirmation.token,maxUsd:arm.budget.protectedMaxUsd});assert.equal(result.guardrails.retailerSubmissionNotClaimed,true);assert.ok(result.distribution.acx.finalPackageMissing.includes('retail sample'));assert.ok(result.distribution.spotify.finalPackageMissing.includes('digital voice disclosure'));assert.ok(result.distribution.apple.finalPackageMissing.includes('selected preferred partner'));}finally{await rm(dir,{recursive:true,force:true});}});

test('tampered recipe digest fails closed before batch arm',async()=>{const {p,recipe,preflight}=await recipeAndPreflight();const bad=structuredClone(recipe);bad.localVoiceFinish.semitones=-2;await assert.rejects(()=>buildBookOneQuotaAwareBatchArm({productionPlan:p,recipeLock:bad,preflight,provider:provider(),ffmpeg:ffmpeg(),outputRoot:'/tmp/yasready-batch-arm',storageProbe:disk(100)}),/recipe lock integrity digest mismatch/i);});

test('tampered full-book preflight fails closed before batch arm',async()=>{const {p,recipe,preflight}=await recipeAndPreflight();const bad=structuredClone(preflight);bad.provider.providerReportedRemaining=999999;await assert.rejects(()=>buildBookOneQuotaAwareBatchArm({productionPlan:p,recipeLock:recipe,preflight:bad,provider:provider(),ffmpeg:ffmpeg(),outputRoot:'/tmp/yasready-batch-arm',storageProbe:disk(100)}),/preflight integrity digest mismatch/i);});
